FROM node:14 AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build --prod

FROM nginx:stable-alpine

COPY --from=builder /app/dist/kanban-ui /usr/share/nginx/html
COPY nginx-frontend.conf etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
