name: Simple Docker Compose Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and start all services
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create .env file
        run: |
          echo "POSTGRES_DB=kanban" > .env
          echo "POSTGRES_USER=user" >> .env
          echo "POSTGRES_PASSWORD=password" >> .env
      - name: Build and start services
        run: docker compose up -d --build
      - name: Stop all services
        run: docker compose down
