name: Kanban Demo CI/CD

on:
  push:
    branches: [main, task8]

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Set up Java 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Build backend with Maven
        run: mvn -B package -f kanban-backend/pom.xml

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-

      - name: Set up Node.js 12
        uses: actions/setup-node@v4
        with:
          node-version: '12'

      - name: Build frontend
        run: |
          cd kanban-frontend
          npm install --legacy-peer-deps
          npm run build -- --prod

  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: build

    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        options: >-
          --health-cmd="pg_isready -U ${{ secrets.POSTGRES_USER }} -d ${{ secrets.POSTGRES_DB }}"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=12

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Run backend unit tests
        run: mvn -B test -f kanban-backend/pom.xml
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/${{ secrets.POSTGRES_DB }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.POSTGRES_USER }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop

  lint:
    name: Lint code
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js 12
        uses: actions/setup-node@v4
        with:
          node-version: '12'
      - name: Install dependencies
        run: cd kanban-frontend && npm install --legacy-peer-deps
      - name: Lint frontend
        run: cd kanban-frontend && npm run lint -- --force

  docker-build:
    needs:
      - build
      - test
      - lint
    name: Build Docker images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        run: |
          docker build -t ${{ secrets.DOCKER_REGISTRY }}/kanban-backend:latest ./kanban-backend
          docker push ${{ secrets.DOCKER_REGISTRY }}/kanban-backend:latest

      - name: Build and push frontend image
        run: |
          docker build -t ${{ secrets.DOCKER_REGISTRY }}/kanban-frontend:latest ./kanban-frontend
          docker push ${{ secrets.DOCKER_REGISTRY }}/kanban-frontend:latest

      - name: Build and push nginx image
        run: |
          docker build -t ${{ secrets.DOCKER_REGISTRY }}/kanban-nginx:latest -f ./kanban-frontend/Dockerfile ./kanban-frontend
          docker push ${{ secrets.DOCKER_REGISTRY }}/kanban-nginx:latest

  deploy:
    name: Deploy to server
    needs: docker-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Copy project files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          source: "."
          target: "/home/${{ secrets.DEPLOY_USER }}/kanban-app"
          port: 22

      - name: Run docker compose on remote server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 22
          script: |
            cd /home/${{ secrets.DEPLOY_USER }}/kanban-app
            docker compose pull
            docker compose up -d --remove-orphans
